### ISSUE TITLE
Custom model demos and documentations

### ISSUE THREAD

**Issue by THE-T-V1RUS** [voxell-tech/UnityNLP#3]
Can you provide a tutorial on how to make a custom model for the NLPNaiveBayesClassifier? I am working on a game project similar to the game "Façade" and I feel the NLPNaiveBayesClassifier along with custom models would be very helpful for this task.

**Comment by nixonyh** [comment]
Hi, this is related to Issue: https://github.com/voxell-tech/UnityNLP/issues/1

**Comment by nixonyh** [comment]
Hi @MYLKCLUB , just so you know I have updated the tutorial on training custom naive bayes classifier here: https://unitynlp.readthedocs.io/en/latest/classifier.html#classifying-a-sentence (refer to #1 for more info)

**Comment by THE-T-V1RUS** [comment]
Hi,

Thank you so much for the example. I tested it out and have it working. I
supported you on ko-fi for the quick response and helpful documentation.
Looking forward to seeing more of your work and buying you more coffee in
the future.

Cheers!
- Brad
(a.k.a. THE_T_V1RUS)

**Comment by nixonyh** [comment]
Hey, thank you so much for your support! I really do appreciate it really much!
