### ISSUE TITLE
The name 'ConfigurationManager' does not exist in the current context

### ISSUE THREAD

**Issue by Wyldhunt** [voxell-tech/UnityNLP#4]
I get the following error when I try to use this in Unity 2020.3:
VoxellNLP\Coreference\Mention\DictionaryFactory.cs(56,24): error CS0103: The name 'ConfigurationManager' does not exist in the current context

using System.Configuration; is properly called, but it can't find using System.Configuration.ConfigurationManager.

Is this a bug or a feature? ... Or, just me?

**Comment by ttttotem** [comment]
Try this:
Edit -> Project Settings -> Player -> Api Compatibility Level
Set it to .NET 4.x

I think this is what fixed it for me

**Comment by nixonyh** [comment]
@Wyldhunt hey, does the suggestion given by @2373655r solved your issue? (am just curious haha)

**Comment by Wyldhunt** [comment]
Unknown. I had to uninstall it. I haven't had a chance to reinstall it to test yet.

**Comment by nixonyh** [comment]
Hey, I am closing this issue for now, seems like @2373655r found a solution to this problem I guess..
