### ISSUE TITLE
Missing namespaces

### ISSUE THREAD

**Issue by Wholebitmedia** [voxell-tech/UnityNLP#7]
I successfully cloned all the necessary repositories from GitHub desktop into unity but there were a lot of missing namespaces.  Is there another repository besides the UnityAI,NLP,Util, and the models package that needs to be cloned?  This repository makes reference to a Cherub and well as another referenced NLP resource.  Any help would be appreciated.

Using WIn11 Unity 2019.4

**Comment by nixonyh** [comment]
hey there, a screenshot or a copy of the errors of missing namespaces would be great for me to debug!

**Comment by nixonyh** [comment]
References are purely references in terms of looking at their code or copy and pasting in. There are no dependencies towards those repositories/code.

**Comment by Wholebitmedia** [comment]
Oh yeah, sorry lemme get that.  About 42 in all.

**Comment by Wholebitmedia** [comment]
Installed fresh one with lot fewer problems.  Usually when I fix
somethingng a few more pop up but here is the screenshot.  Incidentally
before I dive into weeks of research what has been your experience/opinion
of the LUIS and/or Catalyst models for C#?

[image: image.png]

**Comment by nixonyh** [comment]
Hey I don't think I can see the image here. You might want to comment on GitHub instead of via email xd.

**Comment by Wholebitmedia** [comment]
Here it is.  What if any is your opinion of those models?
![image](https://user-images.githubusercontent.com/59541099/180272128-88ae5a56-f231-453c-9d3f-31e782d1dcb8.png)

**Comment by nixonyh** [comment]
Ah I see. It's a very minor bug haha. So basically I update UnityUtil frequently and sometimes I break things xd. Will update the package ASAP to fix this up.

**Comment by Wholebitmedia** [comment]
OK Keep me posted...

**Comment by nixonyh** [comment]
As for the models I'm not so sure tho. I have not personally used all of the models yet. And the ones you mentioned are among those.

**Comment by nixonyh** [comment]
hey man, just opened up Unity in 2021 and found no issue, those error above are errors about missing stuff from Unity not from my packages. I am not sure why your 2020 doesn't have those.. try upgrading Unity to latest LTS and load the project again.

**Comment by Wholebitmedia** [comment]
Opened in 2022 and everything was installed and error free, then I imported the NLP examples and this happened.  
![image](https://user-images.githubusercontent.com/59541099/180840154-5cf9ab22-549d-408f-a888-b1b37adf73e1.png)

**Comment by nixonyh** [comment]
ok I might need to update the samples

**Comment by nixonyh** [comment]
hmm.. not sure why, it works for me though, just to be safe, make sure to use the develop branch and also pull the latest changes
![image](https://user-images.githubusercontent.com/43715558/181028694-783d4343-a12c-45c2-800f-2824899b17c0.png)

**Comment by Wholebitmedia** [comment]
Working form 2020.3.22 now after downloading the develop versions and installing from disk.(github link didn't work) Also Util and NLP will not import until after the models are imported.  Getting 4 console errors:

UnityNLP-develop\UnityNLP-develop\Runtime\VoxellNLP\Coreference\Mention\DictionaryFactory.cs(56,24): error CS0103: The name 'ConfigurationManager' does not exist in the current context

UnityUtil-develop\UnityUtil-develop\Editor\EditorList\EditorListUtil.cs(26,12): error CS1061: 'ReorderableList' does not contain a definition for 'multiSelect' and no accessible extension method 'multiSelect' accepting a first argument of type 'ReorderableList' could be found (are you missing a using directive or an assembly reference?)

UnityUtil-develop\UnityUtil-develop\Editor\EditorBase\VXDefaultEditor.cs(54,11): error CS0246: The type or namespace name 'PrefabStage' could not be found (are you missing a using directive or an assembly reference?)

UnityUtil-develop\UnityUtil-develop\Editor\EditorBase\VXDefaultEditor.cs(54,31): error CS0103: The name 'PrefabStageUtility' does not exist in the current context

**Comment by nixonyh** [comment]
please use 2021 or higher thanks

**Comment by Wholebitmedia** [comment]
Using the latest version 2022.2 achieved one error, looked it up deleted the Library folder, still there 📦 

error CS0006: Metadata file 'System.Configuration.dll' could not be found

**Comment by nixonyh** [comment]
ah this prob, I don't know why some comp works and some don't, I suspect that you will need to have the dll downloaded in your machine via the nuget package manager on visual studio, but I might be wrong..

fyi, I included it via a simple script here instead of the actual dll: https://github.com/voxell-tech/UnityNLP/blob/master/Runtime/VoxellNLP/csc.rsp

**Comment by Wholebitmedia** [comment]
Should I put that csc.rsp file in my Library folder somewhere?  Did that same error.  If possible could you upload a zip of that test you made for comparison?

**Comment by Rafhly** [comment]
This worked for me.
-Created a new project with the 2021.3.6f1 version of unity
-Changed scripting Backend to IL2CPP
-Changed api compatibility to .NET Framework

I then just proceeded to import all the packages. I also encountered problems with system.configuration but this did the trick.
(if your system.configuration is still missing, have you tried adding it as reference?)

However in the end I still end up with several warnings.

**Comment by nixonyh** [comment]
Hey @Rafhly thanks so much! Yeah that might be it, the IL2CPP and .Net thingi.

What warnings did you encounter tho? Would like to know about them.

**Comment by Wholebitmedia** [comment]
Thanks @Rafhly!  Changed scripting and compatibility and no errors but this warning:

Assembly for Assembly Definition File 'Packages/voxell.ai/Runtime/VX.AI.Runtime.asmdef' will not be compiled, because it has no scripts associated with it.
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:CompileScripts (UnityEditor.Scripting.ScriptCompilation.EditorScriptCompilationOptions,UnityEditor.BuildTargetGroup,UnityEditor.BuildTarget,int,string[])

Anyway, the example scene is working great!

**Comment by nixonyh** [comment]
@Wholebitmedia great to hear about that! oh yeah the warning can be safely ignored, it's just missing scripts in a folder that contains an assembly definition. Will take a look at what I can do with it, either remove it or start adding scripts.

**Comment by Rafhly** [comment]
@Wholebitmedia Glad it worked! and yes those were the warning signs @nixon-voxell haha but good to know that they can be safely ignored. Thanks!

**Comment by Wholebitmedia** [comment]
Asking about the json data for the trainer. I have several sentences in my data that are in this format: "I/they/it/when you" will it not work unless I break up into:  I when you....They when you etc.  Or will not work unless it is complete?  Should I leave spaces in between slashes?  I want it to recognize/classify when these two segments  (pronoun + adverb) are in the same sentence in this order.  Is the classifier "wholistic" so to speak?

**Comment by nixonyh** [comment]
I think you will need to break them up. But you can always just modify the source code to make it work the way you want, or just make a custom text post processing to break them up before it is being passed to the "trainer". Btw do join the discord server for questions like this xd.
