### ISSUE TITLE
error CS0006: Metadata file 'System.Configuration.dll' could not be found

### ISSUE THREAD

**Issue by abdxllah** [voxell-tech/UnityNLP#8]
Hi when cloning the UnityNLP folder into Packages, once I open Unity I get this error. Do you have any idea why this happens? Many thanks

**Comment by nixonyh** [comment]
hi there, it's resolved here: https://github.com/voxell-tech/UnityNLP/issues/4

**Comment by nixonyh** [comment]
basically use the other .Net, do not use the .Net 2.1

**Comment by abdxllah** [comment]
thank you!
